name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      shell: bash
      env:
        CC:   gcc-10
        CXX:  g++-10
      run: g++ -o test test.cc -std=c++20 -lpthread && ./test
